name: Build and deploy ASP.Net Core app to Azure Web App - task-management-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore Management-System-Backend/ManagementSystem.sln

      - name: Build
        run: dotnet build Management-System-Backend/ManagementSystem.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish Management-System-Backend/src/ManagementSystem.Api/ManagementSystem.Api.csproj --configuration Release --no-build --output "${{ github.workspace }}/publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8AF8984921A14EA6A027FE6F8BB0D16A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_02C88AF266CA415A8197CAC15EFA3B2E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17EEDCEE247A4EB19E7D2ED9756D664C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'task-management-api'
          slot-name: 'Production'
          package: ./publish
